#pragma once

#include <vector>
#include <string>

namespace lua {

	inline std::string loadingLua = R"(

		SCREEN_WIDTH = $SCREEN_WIDTH
		SCREEN_HEIGHT = $SCREEN_HEIGHT

		LD_PICTURE_OFFX = 31
		LD_PICTURE_OFFY = SCREEN_HEIGHT - SCREEN_HEIGHT / 24 - 46

		LD_PROCESS1_OFFX = 246
		LD_PROCESS2_OFFX = 273
		LD_PROCESS3_OFFX = 300
		LD_PROCESS_OFFY = SCREEN_HEIGHT - SCREEN_HEIGHT / 24 - 46

		GAUGE_BOTTOM_OFFY = SCREEN_HEIGHT / 24
		LD_GAUGE_OFFY = SCREEN_HEIGHT - GAUGE_BOTTOM_OFFY

		GAUGE_HEIGHT = SCREEN_HEIGHT / 65.4545454545

		dofile("UI\\loading_id.lua")

		SCREEN_WIDTH = $SCREEN_WIDTH
		SCREEN_HEIGHT = $SCREEN_HEIGHT   

		dofile("UI\\loading_res.lua")

		SCREEN_WIDTH = $SCREEN_WIDTH
		SCREEN_HEIGHT = $SCREEN_HEIGHT   

		--dofile("UI\\loading_screen.lua") BELOW:

		CreateDialog(UI_IDD_BACK, 0, 0, SCREEN_WIDTH, SCREEN_HEIGHT, NULL_WINDOW_TITLE, 8, 0, UIRECT_ONE)
		CreateGauge(UI_IDD_BACK, UI_IDG_BACK_LOADING, 0, LD_GAUGE_OFFY, SCREEN_WIDTH, GAUGE_HEIGHT, 5, LOADING_RES_BASE+0)

		CreatePictureBox(UI_IDD_BACK, UI_IDP_BACK_LOADING, LD_PICTURE_OFFX, LD_PICTURE_OFFY, 217, 37, 4, LOADING_RES_BASE+1, UIRECT_ONE)
		CreatePictureBox(UI_IDD_BACK, UI_IDP_BACK_PROCESS1, LD_PROCESS1_OFFX, LD_PROCESS_OFFY, 33, 36, 4, LOADING_RES_BASE+2, UIRECT_ONE)
		CreatePictureBox(UI_IDD_BACK, UI_IDP_BACK_PROCESS2, LD_PROCESS2_OFFX, LD_PROCESS_OFFY, 33, 36, 4, LOADING_RES_BASE+2, UIRECT_ONE)
		CreatePictureBox(UI_IDD_BACK, UI_IDP_BACK_PROCESS3, LD_PROCESS3_OFFX, LD_PROCESS_OFFY, 33, 36, 4, LOADING_RES_BASE+2, UIRECT_ONE)

		AllDialogSortingLayer()


	)";

}