#pragma once

#include <string>
#include <vector>

namespace lua {
#ifdef V2013
	inline std::string loginLua = R"(

		dofile("UI\\GlobalVar.lua")
		dofile("UI\\mnemonic.lua")
		dofile("UI\\common_res.lua")
		dofile("UI\\login_res.lua")
		dofile("UI\\StringTable.lua")

		--dofile("UI\\define_default.lua") BELOW:

		---------------------------------------------
		SCREEN_WIDTH = $SCREEN_WIDTH
		SCREEN_HEIGHT = $SCREEN_HEIGHT

		------------ Square MainBar(squarebar.lua)
		MAINBAR_OFFX = SCREEN_WIDTH - 206
		MAINBAR_OFFY = SCREEN_HEIGHT - 69
		MAINMENU_OFFX = SCREEN_WIDTH - 169
		MAINMENU_OFFY = 1

		------------ Square Minimap(squaremap.lua)
		SQMINIMAP_OFFX = SCREEN_WIDTH - 169
		SQMINIMAP_OFFY = 35

		------------ NoteBox(notebox.lua)
		NOTEBOX_OFFX = SCREEN_WIDTH - 201
		NOTEBOX_OFFY = SCREEN_HEIGHT - 172

		------------ CurrentState(currentstate.lua)
		SQUARE_NAME_OFFX = SCREEN_WIDTH / 2 - 109

		------------ Square Chatting & Tip(Square_chatting.lua)
		SQCHATVIEW_OFFX = 0
		SQCHATVIEW_OFFY = SCREEN_HEIGHT - 156
		SQCHATEDIT_OFFX = 0
		SQCHATEDIT_OFFY = SCREEN_HEIGHT - 34
		SQTIP_OFFX = 0
		SQTIP_OFFY = SCREEN_HEIGHT - 18
		SQTIP_WIDTH = SCREEN_WIDTH - 209

		------------ Character View(character_view.lua)
		CHARVIEW_OFFX = SCREEN_WIDTH / 2 - 548 / 2 - 254 / 2
		CHARVIEW_OFFY = SCREEN_HEIGHT / 2 - 565 / 2

		------------ Npc Talk(First Square)(firstinsquare.lua)
		FIRSTSQ_UPPER_OFFX = SCREEN_WIDTH / 2 - 400
		FIRSTSQ_UPPER_OFFY = 0
		FIRSTSQ_LOWER_OFFX = SCREEN_WIDTH / 2 - 400
		FIRSTSQ_LOWER_OFFY = SCREEN_HEIGHT - 240

		------------ Messenger(messenger.lua)
		MSG_OFFX = SCREEN_WIDTH - 201
		MSG_OFFY = SCREEN_HEIGHT - 303
		MSG_FRLIST_OFFX = SCREEN_WIDTH - 401
		MSG_FRLIST_OFFY = SCREEN_HEIGHT - 322
		MSG_MEMO_OFFX = 0
		MSG_MEMO_OFFY = SCREEN_HEIGHT - 157
		MSG_MEMOVIEW_OFFX = 0
		MSG_MEMOVIEW_OFFY = SCREEN_HEIGHT - 138
		MSG_MEMOEDIT_OFFX = 0
		MSG_MEMOEDIT_OFFY = SCREEN_HEIGHT - 138
		MSG_CONNECTFRIEND_OFFX = SCREEN_WIDTH / 2 - 41
		MSG_CONNECTFRIEND_OFFY = SCREEN_HEIGHT / 2 - 102

		------------ Function Card Use(funcitem.lua)
		FUNCITEM_OFFX = 339
		FUNCITEM_OFFY = 263

		------------ Guide Movie(guide.lua)
		GUIDE_MOVIE_OFFX = 234
		GUIDE_MOVIE_OFFY = 175

		------------ Trade(usertrade.lua)
		MY_INVEN_OFFX = SCREEN_WIDTH / 2 - 800 / 2
		MY_INVEN_OFFY = SCREEN_HEIGHT / 2 - 407 / 2

		OTHER_TRADE_OFFX = SCREEN_WIDTH / 2 - 800 / 2 + 636
		OTHER_TRADE_OFFY = SCREEN_HEIGHT / 2 - 407 / 2

		------------ Inventory(inventory.lua)
		INVENTORY_OFFX = SCREEN_WIDTH / 2 - 548 / 2 + 254 / 2
		INVENTORY_OFFY = SCREEN_HEIGHT / 2 - 565 / 2

		------------ CardSlot(cardslot.lua)
		CARDSLOT_OFFX = SCREEN_WIDTH / 2 - 147
		CARDSLOT_OFFY = SCREEN_HEIGHT / 2 - 282

		------------ Survey(surveyui.lua)
		SURVEY_VIEW_OFFX = 319
		SURVEY_VIEW_OFFY = 112
		SURVEY_CONF_OFFX = 339
		SURVEY_CONF_OFFY = 324

		------------ Screen Shot Offset
		SCREEN_SHOT_OFFX = SCREEN_WIDTH / 2 - 350 / 2
		SCREEN_SHOT_OFFY = SCREEN_HEIGHT - 85

		------------ Npc_Talk
		NPC_TALK_OFFX = SCREEN_WIDTH / 2 - 400
		NPC_TALK_OFFY = SCREEN_HEIGHT - 378

		dofile("UI\\common_ui.lua")

		SCREEN_WIDTH = $SCREEN_WIDTH
		SCREEN_HEIGHT = $SCREEN_HEIGHT

		UI_IDD_BACK     = 0 

		UI_IDD_SCREENSHOT = 10
		UI_IDS_SCREENSHOT = UI_IDD_SCREENSHOT+1

		UI_IDD_USABLE_GRADE = 20

		UI_IDD_LOGIN = 100
		UI_IDC_LOGIN_CAPTION = UI_IDD_LOGIN+1
		UI_IDE_LOGIN_ID = UI_IDD_LOGIN+2
		UI_IDE_LOGIN_PASSWD = UI_IDD_LOGIN+3
		UI_IDB_LOGIN_START = UI_IDD_LOGIN+4
		UI_IDB_LOGIN_QUIT = UI_IDD_LOGIN+5
		UI_IDB_LOGIN_SAVE_ID = UI_IDD_LOGIN+6
		UI_IDS_LOGIN_ID = UI_IDD_LOGIN+7
		UI_IDS_LOGIN_PASSWD = UI_IDD_LOGIN+8
		UI_IDW_LOGIN_BOX = UI_IDD_LOGIN+9
		UI_IDP_LOGIN_CAPTION = UI_IDD_LOGIN+10
		UI_IDC_LOGIN_SAVE_ID = UI_IDD_LOGIN+11
		UI_IDS_LOGIN_SAVE_ID_TEXT = UI_IDD_LOGIN+12
		UI_IDB_LOGIN_XBUTTON = UI_IDD_LOGIN+13

		-- Server&Channel Select
		UI_IDD_SERVER_SELECT = 11600

		UI_IDP_SERVER_SELECT_CAPTION = UI_IDD_SERVER_SELECT+1
		UI_IDP_SERVER_SELECT_SVR_CAPTION = UI_IDD_SERVER_SELECT+2
		UI_IDP_SERVER_SELECT_CHN_CAPTION = UI_IDD_SERVER_SELECT+3
		UI_IDW_SERVER_SELECT_INNER = UI_IDD_SERVER_SELECT+4

		UI_IDB_SERVER_SELECT_CLOSE = UI_IDD_SERVER_SELECT+5
		UI_IDB_SERVER_SELECT_XBUTTON = UI_IDD_SERVER_SELECT+6

		UI_IDS_SERVER_SELECT_SCRSVR = UI_IDD_SERVER_SELECT+7
		UI_IDS_SERVER_SELECT_SCRCHN = UI_IDD_SERVER_SELECT+8

		UI_IDS_SERVER_SELECT_MSG = UI_IDD_SERVER_SELECT+9

		-- Server Select
		UI_IDD_SERVER_SELECT_SVR1 = UI_IDD_SERVER_SELECT+20
		UI_IDR_SERVER_SELECT_SVR1_GO = UI_IDD_SERVER_SELECT_SVR1+1
		UI_IDP_SERVER_SELECT_SVR1_TITLE = UI_IDD_SERVER_SELECT_SVR1+2
		UI_IDS_SERVER_SELECT_SVR1_TITLE = UI_IDD_SERVER_SELECT_SVR1+3
		UI_IDP_SERVER_SELECT_SVR1_EDGE = UI_IDD_SERVER_SELECT_SVR1+4

		UI_IDD_SERVER_SELECT_SVR2 = UI_IDD_SERVER_SELECT+30
		UI_IDR_SERVER_SELECT_SVR2_GO = UI_IDD_SERVER_SELECT_SVR2+1
		UI_IDP_SERVER_SELECT_SVR2_TITLE = UI_IDD_SERVER_SELECT_SVR2+2
		UI_IDS_SERVER_SELECT_SVR2_TITLE = UI_IDD_SERVER_SELECT_SVR2+3
		UI_IDP_SERVER_SELECT_SVR2_EDGE = UI_IDD_SERVER_SELECT_SVR2+4

		-- Channel Select
		UI_IDD_SERVER_SELECT_CHN1 = UI_IDD_SERVER_SELECT+40
		UI_IDB_SERVER_SELECT_CHN1_GO = UI_IDD_SERVER_SELECT_CHN1+1
		UI_IDP_SERVER_SELECT_CHN1_TITLE = UI_IDD_SERVER_SELECT_CHN1+2
		UI_IDS_SERVER_SELECT_CHN1_TITLE = UI_IDD_SERVER_SELECT_CHN1+3
		UI_IDP_SERVER_SELECT_CHN1_EDGE1 = UI_IDD_SERVER_SELECT_CHN1+4
		UI_IDP_SERVER_SELECT_CHN1_EDGE2 = UI_IDD_SERVER_SELECT_CHN1+5
		UI_IDP_SERVER_SELECT_CHN1_STATE_BG = UI_IDD_SERVER_SELECT_CHN1+6
		UI_IDG_SERVER_SELECT_CHN1_STATE = UI_IDD_SERVER_SELECT_CHN1+7
		UI_IDS_SERVER_SELECT_CHN1_LIMIT = UI_IDD_SERVER_SELECT_CHN1+8
		UI_IDP_SERVER_SELECT_CHN1_EFFECT = UI_IDD_SERVER_SELECT_CHN1+9

		UI_IDD_SERVER_SELECT_CHN2 = UI_IDD_SERVER_SELECT+60
		UI_IDB_SERVER_SELECT_CHN2_GO = UI_IDD_SERVER_SELECT_CHN2+1
		UI_IDP_SERVER_SELECT_CHN2_TITLE = UI_IDD_SERVER_SELECT_CHN2+2
		UI_IDS_SERVER_SELECT_CHN2_TITLE = UI_IDD_SERVER_SELECT_CHN2+3
		UI_IDP_SERVER_SELECT_CHN2_EDGE1 = UI_IDD_SERVER_SELECT_CHN2+4
		UI_IDP_SERVER_SELECT_CHN2_EDGE2 = UI_IDD_SERVER_SELECT_CHN2+5
		UI_IDP_SERVER_SELECT_CHN2_STATE_BG = UI_IDD_SERVER_SELECT_CHN2+6
		UI_IDG_SERVER_SELECT_CHN2_STATE = UI_IDD_SERVER_SELECT_CHN2+7
		UI_IDS_SERVER_SELECT_CHN2_LIMIT = UI_IDD_SERVER_SELECT_CHN2+8
		UI_IDP_SERVER_SELECT_CHN2_EFFECT = UI_IDD_SERVER_SELECT_CHN2+9

		UI_IDD_SERVER_SELECT_CHN3 = UI_IDD_SERVER_SELECT+80
		UI_IDB_SERVER_SELECT_CHN3_GO = UI_IDD_SERVER_SELECT_CHN3+1
		UI_IDP_SERVER_SELECT_CHN3_TITLE = UI_IDD_SERVER_SELECT_CHN3+2
		UI_IDS_SERVER_SELECT_CHN3_TITLE = UI_IDD_SERVER_SELECT_CHN3+3
		UI_IDP_SERVER_SELECT_CHN3_EDGE1 = UI_IDD_SERVER_SELECT_CHN3+4
		UI_IDP_SERVER_SELECT_CHN3_EDGE2 = UI_IDD_SERVER_SELECT_CHN3+5
		UI_IDP_SERVER_SELECT_CHN3_STATE_BG = UI_IDD_SERVER_SELECT_CHN3+6
		UI_IDG_SERVER_SELECT_CHN3_STATE = UI_IDD_SERVER_SELECT_CHN3+7
		UI_IDS_SERVER_SELECT_CHN3_LIMIT = UI_IDD_SERVER_SELECT_CHN3+8
		UI_IDP_SERVER_SELECT_CHN3_EFFECT = UI_IDD_SERVER_SELECT_CHN3+9

		UI_IDD_SERVER_SELECT_CHN4 = UI_IDD_SERVER_SELECT+100
		UI_IDB_SERVER_SELECT_CHN4_GO = UI_IDD_SERVER_SELECT_CHN4+1
		UI_IDP_SERVER_SELECT_CHN4_TITLE = UI_IDD_SERVER_SELECT_CHN4+2
		UI_IDS_SERVER_SELECT_CHN4_TITLE = UI_IDD_SERVER_SELECT_CHN4+3
		UI_IDP_SERVER_SELECT_CHN4_EDGE1 = UI_IDD_SERVER_SELECT_CHN4+4
		UI_IDP_SERVER_SELECT_CHN4_EDGE2 = UI_IDD_SERVER_SELECT_CHN4+5
		UI_IDP_SERVER_SELECT_CHN4_STATE_BG = UI_IDD_SERVER_SELECT_CHN4+6
		UI_IDG_SERVER_SELECT_CHN4_STATE = UI_IDD_SERVER_SELECT_CHN4+7
		UI_IDS_SERVER_SELECT_CHN4_LIMIT = UI_IDD_SERVER_SELECT_CHN4+8
		UI_IDP_SERVER_SELECT_CHN4_EFFECT = UI_IDD_SERVER_SELECT_CHN4+9

		------------------------------------------------------- Create Char
		UI_IDD_CREATE_CHAR = 27100
		UI_IDP_CREATE_CHAR_MAIN_CAPTION = UI_IDD_CREATE_CHAR+1
		UI_IDP_CREATE_CHAR_DESC_CAPTION = UI_IDD_CREATE_CHAR+2
		UI_IDP_CREATE_CHAR_ABILITY_CAPTION = UI_IDD_CREATE_CHAR+3
		UI_IDP_CREATE_CHAR_RECOMMEND_CAPTION = UI_IDD_CREATE_CHAR+4

		UI_IDS_CREATE_CHAR_MAIN = UI_IDD_CREATE_CHAR+5
		UI_IDS_CREATE_CHAR_DESC = UI_IDD_CREATE_CHAR+6
		UI_IDS_CREATE_CHAR_ABILITY = UI_IDD_CREATE_CHAR+7
		UI_IDS_CREATE_CHAR_RECOMMEND = UI_IDD_CREATE_CHAR+8

		UI_IDW_CREATE_CHAR_INNER = UI_IDD_CREATE_CHAR+9
		UI_IDB_CREATE_CHAR_KEN = UI_IDD_CREATE_CHAR+10
		UI_IDB_CREATE_CHAR_HANA = UI_IDD_CREATE_CHAR+11
		UI_IDB_CREATE_CHAR_KUMA = UI_IDD_CREATE_CHAR+12
		UI_IDB_CREATE_CHAR_MIUMIU = UI_IDD_CREATE_CHAR+13
		UI_IDB_CREATE_CHAR_URU = UI_IDD_CREATE_CHAR+14
		UI_IDB_CREATE_CHAR_SAI = UI_IDD_CREATE_CHAR+15

		UI_IDP_CREATE_CHAR_KEN = UI_IDD_CREATE_CHAR+16
		UI_IDP_CREATE_CHAR_HANA = UI_IDD_CREATE_CHAR+17
		UI_IDP_CREATE_CHAR_KUMA = UI_IDD_CREATE_CHAR+18
		UI_IDP_CREATE_CHAR_MIUMIU = UI_IDD_CREATE_CHAR+19
		UI_IDP_CREATE_CHAR_URU = UI_IDD_CREATE_CHAR+20
		UI_IDP_CREATE_CHAR_SAI = UI_IDD_CREATE_CHAR+21

		UI_IDB_CREATE_CHAR_CREATE = UI_IDD_CREATE_CHAR+22
		UI_IDB_CREATE_CHAR_CLOSE = UI_IDD_CREATE_CHAR+23
		UI_IDB_CREATE_CHAR_XBUTTON = UI_IDD_CREATE_CHAR+24

		------------------------------------------------------- Create Nick
		UI_IDD_CREATE_NICK = 27200
		UI_IDW_CREATE_NICK_INNER = UI_IDD_CREATE_NICK+1
		UI_IDP_CREATE_NICK_MAIN_CAPTION = UI_IDD_CREATE_NICK+2

		UI_IDP_CREATE_NICK_SET_CAPTION = UI_IDD_CREATE_NICK+3
		UI_IDP_CREATE_NICK_REF_CAPTION = UI_IDD_CREATE_NICK+4

		UI_IDS_CREATE_NICK_SET_DESC = UI_IDD_CREATE_NICK+5
		UI_IDS_CREATE_NICK_REF_DESC = UI_IDD_CREATE_NICK+6

		UI_IDS_CREATE_NICK_SET_NICKNAME = UI_IDD_CREATE_NICK+7
		UI_IDS_CREATE_NICK_REF_NICKNAME = UI_IDD_CREATE_NICK+8

		UI_IDE_CREATE_NICK_SET_INPUT = UI_IDD_CREATE_NICK+9
		UI_IDE_CREATE_NICK_REF_INPUT = UI_IDD_CREATE_NICK+10

		UI_IDB_CREATE_NICK_SET_CHECK = UI_IDD_CREATE_NICK+11
		UI_IDB_CREATE_NICK_REF_CHECK = UI_IDD_CREATE_NICK+12

		UI_IDB_CREATE_NICK_CREATE = UI_IDD_CREATE_NICK+13
		UI_IDB_CREATE_NICK_CLOSE = UI_IDD_CREATE_NICK+14
		UI_IDB_CREATE_NICK_XBUTTON = UI_IDD_CREATE_NICK+15

		----------------------------------------------------------------------------

		CreateDialog(UI_IDD_BACK, 0, 0, SCREEN_WIDTH, SCREEN_HEIGHT, NULL_WINDOW_TITLE, 100, 0, UIRECT_ONE)

		CreateDialog(UI_IDD_USABLE_GRADE, 669, 3, 128, 90, NULL_WINDOW_TITLE, 99, 1, UIRECT_ONE)
		HideDialog(UI_IDD_USABLE_GRADE)

		CreateDialog(UI_IDD_LOGIN, $SCREEN_WIDTH / 2 - 272 / 2, $SCREEN_HEIGHT / 2 - 152 / 2, 272, 152, NULL_WINDOW_TITLE, 10, COMMON_RES_BASE+0, UIRECT_NINE)

		CreateWorkGroupBox(UI_IDD_LOGIN, UI_IDW_LOGIN_BOX, 6, 34, 260, 79, 10, COMMON_RES_BASE+3, UIRECT_NINE)   

		CreateStatic(UI_IDD_LOGIN, UI_IDS_LOGIN_ID, 12, 44, 105, 12, STR_ACCOUNT, 2, COMMON_RES_BASE+3, UIRECT_NONE)
			StaticTextDir(UI_IDS_LOGIN_ID, TextDir_Center)    

		CreateStatic(UI_IDD_LOGIN , UI_IDS_LOGIN_PASSWD, 12, 68, 105, 12, STR_PASSWORD, 2, COMMON_RES_BASE+3, UIRECT_NONE)
			StaticTextDir(UI_IDS_LOGIN_PASSWD, TextDir_Center)    
 
		CreateMultiLangEditBox( UI_IDD_LOGIN, UI_IDE_LOGIN_ID, 121, 40, 140, 20, STR_CONTROL_NULL, 3, COMMON_RES_BASE+0, UIRECT_NINE)
		CreatePasswordEdit(UI_IDD_LOGIN, UI_IDE_LOGIN_PASSWD, 121, 64, 140, 20, 3, COMMON_RES_BASE+0, UIRECT_NINE) 

		CreateCheckBox(UI_IDD_LOGIN , UI_IDC_LOGIN_SAVE_ID, 121, 91, 14, 14, FALSE, 2, COMMON_RES_BASE+1, UIRECT_ONE)
		CreateStatic(UI_IDD_LOGIN , UI_IDS_LOGIN_SAVE_ID_TEXT, 139, 92, 122, 12, GetText("Login","SaveID"), 2, COMMON_RES_BASE+3, UIRECT_NONE)
			StaticTextDir(UI_IDS_LOGIN_SAVE_ID_TEXT, TextDir_Left)
 
		CreateButton(UI_IDD_LOGIN, UI_IDB_LOGIN_START, 55, 115, 83, 30, "", 0, LOGIN_RES_BASE+0, UIRECT_ONE)
		CreateButton(UI_IDD_LOGIN, UI_IDB_LOGIN_QUIT, 142, 115, 83, 30, "", 0, LOGIN_RES_BASE+1, UIRECT_ONE)
		CreateButton(UI_IDD_LOGIN, UI_IDB_LOGIN_XBUTTON, 240, 7, 25, 25, "", 0, COMMON_RES_BASE+4, UIRECT_ONE)
    
		CreatePictureBox(UI_IDD_LOGIN , UI_IDP_LOGIN_CAPTION, 36, 13, 200, 14, 1, LOGIN_RES_BASE+0, UIRECT_ONE)

		dofile("UI\\server_select.lua")
		dofile("UI\\logoeffect.lua")
		dofile("UI\\character_create.lua")

		CreateNullDialog( UI_IDD_SCREENSHOT, 256, 530, 450, 20, -2)
		CreateStatic(UI_IDD_SCREENSHOT, UI_IDS_SCREENSHOT, 0, 0, 450, 20, STR_NULL, -1, COMMON_RES_BASE+17, UIRECT_NONE)
			StaticTextDir(UI_IDS_SCREENSHOT, TextDir_Left)  

	)";
#else
    inline std::string loginLua = R"(

		dofile("UI\\GlobalVar.lua")
		dofile("UI\\mnemonic.lua")
		dofile("UI\\common_res.lua")

		--dofile("UI\\login_res.lua") BELOW:

		-- NOTE! THIS NEEDS TO BE THE RESOLUTION OF THE BACKGROUND IMAGE IN ORDER TO SCALE PROPERLY
		CreateTextureInfo(DIALOG, 0, 0, 0, 3840, 2160, RENDER_BLEND, LoginBg)

		CreateTextureInfo(DIALOG, 1, 0, 0, 128, 90, RENDER_BLEND, UIImagePath.."ui-grade-all.dds")
		CreateTextureInfo(DIALOG, 1, 0, 0, 128, 90, RENDER_BLEND, UIImagePath.."ui-grade-12.dds")

		CreateTextureInfo(PICTUREBOX, LOGIN_RES_BASE+0, 0, 0, 200, 14, RENDER_BLEND, Login_Texture)

		CreateTextureInfo(BUTTON, LOGIN_RES_BASE+0, 0, 15, 83, 30, RENDER_BLEND, Login_Texture)
		CreateTextureInfo(BUTTON, LOGIN_RES_BASE+0, 0, 46, 83, 30, RENDER_BLEND, Login_Texture)
		CreateTextureInfo(BUTTON, LOGIN_RES_BASE+0, 0, 77, 83, 30, RENDER_BLEND, Login_Texture)
		CreateTextureInfo(BUTTON, LOGIN_RES_BASE+0, 168, 15, 83, 30, RENDER_BLEND, Login_Texture)

		CreateTextureInfo(BUTTON, LOGIN_RES_BASE+1, 84, 15, 83, 30, RENDER_BLEND, Login_Texture)
		CreateTextureInfo(BUTTON, LOGIN_RES_BASE+1, 84, 46, 83, 30, RENDER_BLEND, Login_Texture)
		CreateTextureInfo(BUTTON, LOGIN_RES_BASE+1, 84, 77, 83, 30, RENDER_BLEND, Login_Texture)
		CreateTextureInfo(BUTTON, LOGIN_RES_BASE+1, 168, 46, 83, 30, RENDER_BLEND, Login_Texture)

		dofile("UI\\StringTable.lua")

		--dofile("UI\\define_default.lua") BELOW:

		SCREEN_WIDTH = $SCREEN_WIDTH
		SCREEN_HEIGHT = $SCREEN_HEIGHT

		MAINBAR_OFFX = 594
		MAINBAR_OFFY = 531

		MAINMENU_OFFX = 631
		MAINMENU_OFFY = 1

		SQMINIMAP_OFFX = 631
		SQMINIMAP_OFFY = 35

		NOTEBOX_OFFX = 599
		NOTEBOX_OFFY = 427

		SQUARE_NAME_OFFX = 291

		SQCHATVIEW_OFFX = 0
		SQCHATVIEW_OFFY = 443
		SQCHATEDIT_OFFX = 0
		SQCHATEDIT_OFFY = 565

		SQTIP_OFFX = 0
		SQTIP_OFFY = 582
		SQTIP_WIDTH = 595

		CHARVIEW_OFFX = 0
		CHARVIEW_OFFY = 0

		FIRSTSQ_UPPER_OFFX = 0
		FIRSTSQ_UPPER_OFFY = 0
		FIRSTSQ_LOWER_OFFX = 0
		FIRSTSQ_LOWER_OFFY = 358

		MSG_OFFX = 599
		MSG_OFFY = 297
		MSG_FRLIST_OFFX = 399
		MSG_FRLIST_OFFY = 276
		MSG_MEMO_OFFX = 0
		MSG_MEMO_OFFY = 443
		MSG_MEMOVIEW_OFFX = 0
		MSG_MEMOVIEW_OFFY = 462
		MSG_MEMOEDIT_OFFX = 0
		MSG_MEMOEDIT_OFFY = 462
		MSG_CONNECTFRIEND_OFFX = 599
		MSG_CONNECTFRIEND_OFFY = 410

		FUNCITEM_OFFX = 227
		FUNCITEM_OFFY = 157

		GUIDE_MOVIE_OFFX = 122
		GUIDE_MOVIE_OFFY = 91

		MY_INVEN_OFFX = 1
		MY_INVEN_OFFY = 1

		OTHER_TRADE_OFFX = 637
		OTHER_TRADE_OFFY = 1

		INVENTORY_OFFX = 254
		INVENTORY_OFFY = 0

		CARDSLOT_OFFX = 254
		CARDSLOT_OFFY = 0

		SURVEY_VIEW_OFFX = 207
		SURVEY_VIEW_OFFY = 28
		SURVEY_CONF_OFFX = 227
		SURVEY_CONF_OFFY = 240

		SCREEN_SHOT_OFFX = 256
		SCREEN_SHOT_OFFY = 530

		NPC_TALK_OFFX = 0
		NPC_TALK_OFFY = 422

		dofile("UI\\common_ui.lua")

		UI_IDD_BACK     = 0 

		UI_IDD_SCREENSHOT = 10
		UI_IDS_SCREENSHOT = UI_IDD_SCREENSHOT+1

		UI_IDD_USABLE_GRADE = 20

		UI_IDD_LOGIN = 100
		UI_IDC_LOGIN_CAPTION = UI_IDD_LOGIN+1
		UI_IDE_LOGIN_ID = UI_IDD_LOGIN+2
		UI_IDE_LOGIN_PASSWD = UI_IDD_LOGIN+3
		UI_IDB_LOGIN_START = UI_IDD_LOGIN+4
		UI_IDB_LOGIN_QUIT = UI_IDD_LOGIN+5
		UI_IDB_LOGIN_SAVE_ID = UI_IDD_LOGIN+6
		UI_IDS_LOGIN_ID = UI_IDD_LOGIN+7
		UI_IDS_LOGIN_PASSWD = UI_IDD_LOGIN+8
		UI_IDW_LOGIN_BOX = UI_IDD_LOGIN+9
		UI_IDP_LOGIN_CAPTION = UI_IDD_LOGIN+10
		UI_IDC_LOGIN_SAVE_ID = UI_IDD_LOGIN+11
		UI_IDS_LOGIN_SAVE_ID_TEXT = UI_IDD_LOGIN+12
		UI_IDB_LOGIN_XBUTTON = UI_IDD_LOGIN+13

		UI_IDD_SERVER_SELECT = 11600

		UI_IDP_SERVER_SELECT_CAPTION = UI_IDD_SERVER_SELECT+1
		UI_IDP_SERVER_SELECT_SVR_CAPTION = UI_IDD_SERVER_SELECT+2
		UI_IDP_SERVER_SELECT_CHN_CAPTION = UI_IDD_SERVER_SELECT+3
		UI_IDW_SERVER_SELECT_INNER = UI_IDD_SERVER_SELECT+4

		UI_IDB_SERVER_SELECT_CLOSE = UI_IDD_SERVER_SELECT+5
		UI_IDB_SERVER_SELECT_XBUTTON = UI_IDD_SERVER_SELECT+6

		UI_IDS_SERVER_SELECT_SCRSVR = UI_IDD_SERVER_SELECT+7
		UI_IDS_SERVER_SELECT_SCRCHN = UI_IDD_SERVER_SELECT+8

		UI_IDS_SERVER_SELECT_MSG = UI_IDD_SERVER_SELECT+9

		UI_IDD_SERVER_SELECT_SVR1 = UI_IDD_SERVER_SELECT+20
		UI_IDR_SERVER_SELECT_SVR1_GO = UI_IDD_SERVER_SELECT_SVR1+1
		UI_IDP_SERVER_SELECT_SVR1_TITLE = UI_IDD_SERVER_SELECT_SVR1+2
		UI_IDS_SERVER_SELECT_SVR1_TITLE = UI_IDD_SERVER_SELECT_SVR1+3
		UI_IDP_SERVER_SELECT_SVR1_EDGE = UI_IDD_SERVER_SELECT_SVR1+4

		UI_IDD_SERVER_SELECT_SVR2 = UI_IDD_SERVER_SELECT+30
		UI_IDR_SERVER_SELECT_SVR2_GO = UI_IDD_SERVER_SELECT_SVR2+1
		UI_IDP_SERVER_SELECT_SVR2_TITLE = UI_IDD_SERVER_SELECT_SVR2+2
		UI_IDS_SERVER_SELECT_SVR2_TITLE = UI_IDD_SERVER_SELECT_SVR2+3
		UI_IDP_SERVER_SELECT_SVR2_EDGE = UI_IDD_SERVER_SELECT_SVR2+4

		UI_IDD_SERVER_SELECT_CHN1 = UI_IDD_SERVER_SELECT+40
		UI_IDB_SERVER_SELECT_CHN1_GO = UI_IDD_SERVER_SELECT_CHN1+1
		UI_IDP_SERVER_SELECT_CHN1_TITLE = UI_IDD_SERVER_SELECT_CHN1+2
		UI_IDS_SERVER_SELECT_CHN1_TITLE = UI_IDD_SERVER_SELECT_CHN1+3
		UI_IDP_SERVER_SELECT_CHN1_EDGE1 = UI_IDD_SERVER_SELECT_CHN1+4
		UI_IDP_SERVER_SELECT_CHN1_EDGE2 = UI_IDD_SERVER_SELECT_CHN1+5
		UI_IDP_SERVER_SELECT_CHN1_STATE_BG = UI_IDD_SERVER_SELECT_CHN1+6
		UI_IDG_SERVER_SELECT_CHN1_STATE = UI_IDD_SERVER_SELECT_CHN1+7
		UI_IDS_SERVER_SELECT_CHN1_LIMIT = UI_IDD_SERVER_SELECT_CHN1+8
		UI_IDP_SERVER_SELECT_CHN1_EFFECT = UI_IDD_SERVER_SELECT_CHN1+9

		UI_IDD_SERVER_SELECT_CHN2 = UI_IDD_SERVER_SELECT+60
		UI_IDB_SERVER_SELECT_CHN2_GO = UI_IDD_SERVER_SELECT_CHN2+1
		UI_IDP_SERVER_SELECT_CHN2_TITLE = UI_IDD_SERVER_SELECT_CHN2+2
		UI_IDS_SERVER_SELECT_CHN2_TITLE = UI_IDD_SERVER_SELECT_CHN2+3
		UI_IDP_SERVER_SELECT_CHN2_EDGE1 = UI_IDD_SERVER_SELECT_CHN2+4
		UI_IDP_SERVER_SELECT_CHN2_EDGE2 = UI_IDD_SERVER_SELECT_CHN2+5
		UI_IDP_SERVER_SELECT_CHN2_STATE_BG = UI_IDD_SERVER_SELECT_CHN2+6
		UI_IDG_SERVER_SELECT_CHN2_STATE = UI_IDD_SERVER_SELECT_CHN2+7
		UI_IDS_SERVER_SELECT_CHN2_LIMIT = UI_IDD_SERVER_SELECT_CHN2+8
		UI_IDP_SERVER_SELECT_CHN2_EFFECT = UI_IDD_SERVER_SELECT_CHN2+9

		UI_IDD_SERVER_SELECT_CHN3 = UI_IDD_SERVER_SELECT+80
		UI_IDB_SERVER_SELECT_CHN3_GO = UI_IDD_SERVER_SELECT_CHN3+1
		UI_IDP_SERVER_SELECT_CHN3_TITLE = UI_IDD_SERVER_SELECT_CHN3+2
		UI_IDS_SERVER_SELECT_CHN3_TITLE = UI_IDD_SERVER_SELECT_CHN3+3
		UI_IDP_SERVER_SELECT_CHN3_EDGE1 = UI_IDD_SERVER_SELECT_CHN3+4
		UI_IDP_SERVER_SELECT_CHN3_EDGE2 = UI_IDD_SERVER_SELECT_CHN3+5
		UI_IDP_SERVER_SELECT_CHN3_STATE_BG = UI_IDD_SERVER_SELECT_CHN3+6
		UI_IDG_SERVER_SELECT_CHN3_STATE = UI_IDD_SERVER_SELECT_CHN3+7
		UI_IDS_SERVER_SELECT_CHN3_LIMIT = UI_IDD_SERVER_SELECT_CHN3+8
		UI_IDP_SERVER_SELECT_CHN3_EFFECT = UI_IDD_SERVER_SELECT_CHN3+9

		UI_IDD_SERVER_SELECT_CHN4 = UI_IDD_SERVER_SELECT+100
		UI_IDB_SERVER_SELECT_CHN4_GO = UI_IDD_SERVER_SELECT_CHN4+1
		UI_IDP_SERVER_SELECT_CHN4_TITLE = UI_IDD_SERVER_SELECT_CHN4+2
		UI_IDS_SERVER_SELECT_CHN4_TITLE = UI_IDD_SERVER_SELECT_CHN4+3
		UI_IDP_SERVER_SELECT_CHN4_EDGE1 = UI_IDD_SERVER_SELECT_CHN4+4
		UI_IDP_SERVER_SELECT_CHN4_EDGE2 = UI_IDD_SERVER_SELECT_CHN4+5
		UI_IDP_SERVER_SELECT_CHN4_STATE_BG = UI_IDD_SERVER_SELECT_CHN4+6
		UI_IDG_SERVER_SELECT_CHN4_STATE = UI_IDD_SERVER_SELECT_CHN4+7
		UI_IDS_SERVER_SELECT_CHN4_LIMIT = UI_IDD_SERVER_SELECT_CHN4+8
		UI_IDP_SERVER_SELECT_CHN4_EFFECT = UI_IDD_SERVER_SELECT_CHN4+9

		UI_IDD_CREATE_CHAR = 27100
		UI_IDP_CREATE_CHAR_MAIN_CAPTION = UI_IDD_CREATE_CHAR+1
		UI_IDP_CREATE_CHAR_DESC_CAPTION = UI_IDD_CREATE_CHAR+2
		UI_IDP_CREATE_CHAR_ABILITY_CAPTION = UI_IDD_CREATE_CHAR+3
		UI_IDP_CREATE_CHAR_RECOMMEND_CAPTION = UI_IDD_CREATE_CHAR+4

		UI_IDS_CREATE_CHAR_MAIN = UI_IDD_CREATE_CHAR+5
		UI_IDS_CREATE_CHAR_DESC = UI_IDD_CREATE_CHAR+6
		UI_IDS_CREATE_CHAR_ABILITY = UI_IDD_CREATE_CHAR+7
		UI_IDS_CREATE_CHAR_RECOMMEND = UI_IDD_CREATE_CHAR+8

		UI_IDW_CREATE_CHAR_INNER = UI_IDD_CREATE_CHAR+9
		UI_IDB_CREATE_CHAR_KEN = UI_IDD_CREATE_CHAR+10
		UI_IDB_CREATE_CHAR_HANA = UI_IDD_CREATE_CHAR+11
		UI_IDB_CREATE_CHAR_KUMA = UI_IDD_CREATE_CHAR+12
		UI_IDB_CREATE_CHAR_MIUMIU = UI_IDD_CREATE_CHAR+13
		UI_IDB_CREATE_CHAR_URU = UI_IDD_CREATE_CHAR+14
		UI_IDB_CREATE_CHAR_SAI = UI_IDD_CREATE_CHAR+15

		UI_IDP_CREATE_CHAR_KEN = UI_IDD_CREATE_CHAR+16
		UI_IDP_CREATE_CHAR_HANA = UI_IDD_CREATE_CHAR+17
		UI_IDP_CREATE_CHAR_KUMA = UI_IDD_CREATE_CHAR+18
		UI_IDP_CREATE_CHAR_MIUMIU = UI_IDD_CREATE_CHAR+19
		UI_IDP_CREATE_CHAR_URU = UI_IDD_CREATE_CHAR+20
		UI_IDP_CREATE_CHAR_SAI = UI_IDD_CREATE_CHAR+21

		UI_IDB_CREATE_CHAR_CREATE = UI_IDD_CREATE_CHAR+22
		UI_IDB_CREATE_CHAR_CLOSE = UI_IDD_CREATE_CHAR+23
		UI_IDB_CREATE_CHAR_XBUTTON = UI_IDD_CREATE_CHAR+24

		UI_IDD_CREATE_NICK = 27200
		UI_IDW_CREATE_NICK_INNER = UI_IDD_CREATE_NICK+1
		UI_IDP_CREATE_NICK_MAIN_CAPTION = UI_IDD_CREATE_NICK+2

		UI_IDP_CREATE_NICK_SET_CAPTION = UI_IDD_CREATE_NICK+3
		UI_IDP_CREATE_NICK_REF_CAPTION = UI_IDD_CREATE_NICK+4

		UI_IDS_CREATE_NICK_SET_DESC = UI_IDD_CREATE_NICK+5
		UI_IDS_CREATE_NICK_REF_DESC = UI_IDD_CREATE_NICK+6

		UI_IDS_CREATE_NICK_SET_NICKNAME = UI_IDD_CREATE_NICK+7
		UI_IDS_CREATE_NICK_REF_NICKNAME = UI_IDD_CREATE_NICK+8

		UI_IDE_CREATE_NICK_SET_INPUT = UI_IDD_CREATE_NICK+9
		UI_IDE_CREATE_NICK_REF_INPUT = UI_IDD_CREATE_NICK+10

		UI_IDB_CREATE_NICK_SET_CHECK = UI_IDD_CREATE_NICK+11
		UI_IDB_CREATE_NICK_REF_CHECK = UI_IDD_CREATE_NICK+12

		UI_IDB_CREATE_NICK_CREATE = UI_IDD_CREATE_NICK+13
		UI_IDB_CREATE_NICK_CLOSE = UI_IDD_CREATE_NICK+14
		UI_IDB_CREATE_NICK_XBUTTON = UI_IDD_CREATE_NICK+15

		dofile("UI\\legacy_login_res.lua")

		UI_IDD_LOGIN_SCREEN_WIDTH = $SCREEN_WIDTH
		UI_IDD_LOGIN_SCREEN_HEIGHT = $SCREEN_HEIGHT

		UI_IDD_LOGIN_WIDTH = 240
		UI_IDD_LOGIN_HEIGHT = 158

		CreateDialog(UI_IDD_BACK, 0, 0, UI_IDD_LOGIN_SCREEN_WIDTH, UI_IDD_LOGIN_SCREEN_HEIGHT, NULL_WINDOW_TITLE, 10, 0, UIRECT_ONE)
		CreateDialog(UI_IDD_USABLE_GRADE, 669, 3, 128, 90, NULL_WINDOW_TITLE, 99, 1, UIRECT_ONE)
			HideDialog(UI_IDD_USABLE_GRADE)

		CreateDialog(UI_IDD_LOGIN, (UI_IDD_LOGIN_SCREEN_WIDTH / 2) - (UI_IDD_LOGIN_WIDTH / 2), UI_IDD_LOGIN_SCREEN_HEIGHT - (UI_IDD_LOGIN_HEIGHT * 2), UI_IDD_LOGIN_WIDTH, UI_IDD_LOGIN_HEIGHT, NULL_WINDOW_TITLE, 10, LEGACY_COMMON_RES_BASE+0, UIRECT_NINE)

		EnableSkinColor(UI_IDD_LOGIN))"

		R"(

		CreateCaptionBar(UI_IDD_LOGIN, UI_IDC_LOGIN_CAPTION, 14, -22, 112, 24 , 2, LEGACY_COMMON_RES_BASE+0, UIRECT_THREE)
		CreatePictureBox(UI_IDD_LOGIN, UI_IDP_LOGIN_CAPTION, 16, 2, 108, 22, 1, LEGACY_LOGIN_RES_BASE+0, UIRECT_ONE)

		CreateStatic(UI_IDD_LOGIN, UI_IDS_LOGIN_ID, 22, 51, 72, 20, STR_ACCOUNT, 2, LEGACY_COMMON_RES_BASE+0, UIRECT_NONE)
			StaticTextDir(UI_IDS_LOGIN_ID, TextDir_Left)    

		CreateStatic(UI_IDD_LOGIN, UI_IDS_LOGIN_PASSWD, 22, 81, 72, 20, STR_PASSWORD, 2, LEGACY_COMMON_RES_BASE+0, UIRECT_NONE)
			StaticTextDir(UI_IDS_LOGIN_PASSWD, TextDir_Left)

		CreateWorkGroupBox(UI_IDD_LOGIN, UI_IDW_LOGIN_BOX, 13, 35, 214, 101, 10, LEGACY_COMMON_RES_BASE+0, UIRECT_NINE)    

		CreateMultiLangEditBox(UI_IDD_LOGIN, UI_IDE_LOGIN_ID, 96, 45, 121, 21, STR_CONTROL_NULL, 3, LEGACY_COMMON_RES_BASE+0, UIRECT_THREE)

		CreatePasswordEdit(UI_IDD_LOGIN, UI_IDE_LOGIN_PASSWD, 96, 75, 121, 21, 3, LEGACY_COMMON_RES_BASE+0, UIRECT_THREE)

		CreateCheckBox(UI_IDD_LOGIN, UI_IDC_LOGIN_SAVE_ID, 96 , 108, 18, 18 , FALSE, 2, LEGACY_COMMON_RES_BASE+1, UIRECT_ONE)

		CreateStatic(UI_IDD_LOGIN, UI_IDS_LOGIN_SAVE_ID_TEXT, 121, 113, 96, 18, GetText("Login", "SaveID"), 2, LEGACY_COMMON_RES_BASE+0, UIRECT_NONE)
			StaticTextDir(UI_IDS_LOGIN_PASSWD, TextDir_Left)
		CreateButton(UI_IDD_LOGIN, UI_IDB_LOGIN_START, 13, 142, 99, 25 , STR_BUTTON_BEGIN, 0, LEGACY_COMMON_RES_BASE+0 , UIRECT_THREE)
			SetTextGap(UI_IDB_LOGIN_START, 7, 8)
			ControlTextDir(UI_IDB_LOGIN_START, TextDir_Center)
			ButtonRot(UI_IDB_LOGIN_START, RotateY)
			IsButtonDir(UI_IDB_LOGIN_START, TRUE) 
			AttachButtonCraddle(UI_IDB_LOGIN_START, LEGACY_COMMON_RES_BASE+1)
		CreateButton(UI_IDD_LOGIN, UI_IDB_LOGIN_QUIT, 128, 142, 99, 25 , STR_BUTTON_END, 0, LEGACY_COMMON_RES_BASE+0 , UIRECT_THREE)
			SetTextGap(UI_IDB_LOGIN_QUIT, 7, 8)
			ControlTextDir(UI_IDB_LOGIN_QUIT, TextDir_Center)
			ButtonRot(UI_IDB_LOGIN_QUIT, RotateY)    
			IsButtonDir(UI_IDB_LOGIN_QUIT, TRUE) 
			AttachButtonCraddle(UI_IDB_LOGIN_QUIT, LEGACY_COMMON_RES_BASE+1)
		CreateSkinnedPictureBox(UI_IDD_LOGIN, UI_IDP_LOGIN_RUNNER, 0, 78, 15, 15, 5, LEGACY_COMMON_RES_BASE+2, UIRECT_NONE)
		CreateSkinnedPictureBox(UI_IDD_LOGIN, UI_IDP_LOGIN_RUNNER, 225, 78, 15, 15, 5, LEGACY_COMMON_RES_BASE+3, UIRECT_NONE)
		CreateSkinnedPictureBox(UI_IDD_LOGIN, UI_IDP_LOGIN_RUNNER, 55, 165, 15, 15, 5, LEGACY_COMMON_RES_BASE+1, UIRECT_NONE)
		CreateSkinnedPictureBox(UI_IDD_LOGIN, UI_IDP_LOGIN_RUNNER, 170, 165, 15, 15, 5, LEGACY_COMMON_RES_BASE+1, UIRECT_NONE)

		CreateStatic(UI_IDD_BACK, 59997, UI_IDD_LOGIN_SCREEN_WIDTH - 160, 20, 144, 0, STR_MODNAME, 2, LEGACY_LOGIN_RES_BASE+0, UIRECT_NONE)
			StaticTextDir(59997, TextDir_Right)
		CreateStatic(UI_IDD_BACK, 59998, UI_IDD_LOGIN_SCREEN_WIDTH - 160, 40, 144, 0, STR_VERSION, 2, LEGACY_LOGIN_RES_BASE+0, UIRECT_NONE)
			StaticTextDir(59998, TextDir_Right)
		CreateStatic(UI_IDD_BACK, 59999, UI_IDD_LOGIN_SCREEN_WIDTH - 160, 60, 144, 0, STR_CREDIT, 2, LEGACY_LOGIN_RES_BASE+0, UIRECT_NONE)
			StaticTextDir(59999, TextDir_Right)

		CreateStatic(UI_IDD_BACK, 599996, 15, 40, 300, 0, "QPang Tweak Tool", 2, LEGACY_LOGIN_RES_BASE+0, UIRECT_NONE)
			StaticTextDir(599996, TextDir_Left)
		CreateStatic(UI_IDD_BACK, 599997, 15, 60, 300, 0, "v0.1", 2, LEGACY_LOGIN_RES_BASE+0, UIRECT_NONE)
			StaticTextDir(599997, TextDir_Left)
		CreateStatic(UI_IDD_BACK, 599998, 15, 80, 300, 0, "by Hinnie", 2, LEGACY_LOGIN_RES_BASE+0, UIRECT_NONE)
			StaticTextDir(599998, TextDir_Left)
		CreateStatic(UI_IDD_BACK, 599999, 15, 20, 300, 0, "Press [F11] to open menu", 2, LEGACY_LOGIN_RES_BASE+0, UIRECT_NONE)
			StaticTextDir(599999, TextDir_Left)
	
		dofile("UI\\server_select.lua")
		dofile("UI\\logoeffect.lua")
		dofile("UI\\character_create.lua")

		CreateNullDialog( UI_IDD_SCREENSHOT, 256, 530, 450, 20, -2)
		CreateStatic(UI_IDD_SCREENSHOT, UI_IDS_SCREENSHOT, 0, 0, 450, 20, STR_NULL, -1, LEGACY_COMMON_RES_BASE+17, UIRECT_NONE)
			StaticTextDir(UI_IDS_SCREENSHOT, TextDir_Left)    

	)";
#endif
}