#pragma once

#include <vector>
#include <string>

namespace lua {
#ifdef V2013
	inline std::string squareInitLua = R"(

		SCREEN_WIDTH = $SCREEN_WIDTH
		SCREEN_HEIGHT = $SCREEN_HEIGHT   

		-- Prerequisite For All State Entry Point
		dofile("UI\\GlobalVar.lua")

		SCREEN_WIDTH = $SCREEN_WIDTH
		SCREEN_HEIGHT = $SCREEN_HEIGHT   

		dofile("UI\\mnemonic.lua")

		SCREEN_WIDTH = $SCREEN_WIDTH
		SCREEN_HEIGHT = $SCREEN_HEIGHT   

		dofile("UI\\StringTable.lua")

		SCREEN_WIDTH = $SCREEN_WIDTH
		SCREEN_HEIGHT = $SCREEN_HEIGHT   

		dofile("UI\\common_res.lua")

		SCREEN_WIDTH = $SCREEN_WIDTH
		SCREEN_HEIGHT = $SCREEN_HEIGHT   

		dofile("UI\\square_id.lua")

		--------------------------------------------- 
		SCREEN_WIDTH = $SCREEN_WIDTH
		SCREEN_HEIGHT = $SCREEN_HEIGHT

		------------ Square MainBar(squarebar.lua)
		MAINBAR_OFFX = SCREEN_WIDTH - 206
		MAINBAR_OFFY = SCREEN_HEIGHT - 69
		MAINMENU_OFFX = SCREEN_WIDTH - 169
		MAINMENU_OFFY = 1

		------------ Square Minimap(squaremap.lua)
		SQMINIMAP_OFFX = SCREEN_WIDTH - 169
		SQMINIMAP_OFFY = 35

		------------ NoteBox(notebox.lua)
		NOTEBOX_OFFX = SCREEN_WIDTH - 201
		NOTEBOX_OFFY = SCREEN_HEIGHT - 172

		------------ CurrentState(currentstate.lua)
		SQUARE_NAME_OFFX = SCREEN_WIDTH / 2 - 109
		SQUARE_NAME_WIDTH = 0

		------------ Square Chatting & Tip(Square_chatting.lua)
		SQCHATVIEW_OFFX = 0
		SQCHATVIEW_OFFY = SCREEN_HEIGHT - 156
		SQCHATEDIT_OFFX = 0
		SQCHATEDIT_OFFY = SCREEN_HEIGHT - 34
		SQTIP_OFFX = 0
		SQTIP_OFFY = SCREEN_HEIGHT - 18
		SQTIP_WIDTH = SCREEN_WIDTH - 209

		------------ Character View(character_view.lua)
		CHARVIEW_OFFX = SCREEN_WIDTH / 2 - 548 / 2 - 254 / 2
		CHARVIEW_OFFY = SCREEN_HEIGHT / 2 - 565 / 2

		------------ Npc Talk(First Square)(firstinsquare.lua)
		FIRSTSQ_UPPER_OFFX = SCREEN_WIDTH / 2 - 400
		FIRSTSQ_UPPER_OFFY = 0
		FIRSTSQ_LOWER_OFFX = SCREEN_WIDTH / 2 - 400
		FIRSTSQ_LOWER_OFFY = SCREEN_HEIGHT - 240

		------------ Messenger(messenger.lua)
		MSG_OFFX = SCREEN_WIDTH - 201
		MSG_OFFY = SCREEN_HEIGHT - 303
		MSG_FRLIST_OFFX = SCREEN_WIDTH - 401
		MSG_FRLIST_OFFY = SCREEN_HEIGHT - 322
		MSG_MEMO_OFFX = 0
		MSG_MEMO_OFFY = SCREEN_HEIGHT - 157
		MSG_MEMOVIEW_OFFX = 0
		MSG_MEMOVIEW_OFFY = SCREEN_HEIGHT - 138
		MSG_MEMOEDIT_OFFX = 0
		MSG_MEMOEDIT_OFFY = SCREEN_HEIGHT - 138
		MSG_CONNECTFRIEND_OFFX = SCREEN_WIDTH / 2 - 41
		MSG_CONNECTFRIEND_OFFY = SCREEN_HEIGHT / 2 - 102

		------------ Function Card Use(funcitem.lua)
		FUNCITEM_OFFX = 339
		FUNCITEM_OFFY = 263

		------------ Guide Movie(guide.lua)
		GUIDE_MOVIE_OFFX = 234
		GUIDE_MOVIE_OFFY = 175

		------------ Trade(usertrade.lua)
		MY_INVEN_OFFX = SCREEN_WIDTH / 2 - 800 / 2
		MY_INVEN_OFFY = SCREEN_HEIGHT / 2 - 407 / 2

		OTHER_TRADE_OFFX = SCREEN_WIDTH / 2 - 800 / 2 + 636
		OTHER_TRADE_OFFY = SCREEN_HEIGHT / 2 - 407 / 2

		------------ Inventory(inventory.lua)
		INVENTORY_OFFX = SCREEN_WIDTH / 2 - 548 / 2 + 254 / 2
		INVENTORY_OFFY = SCREEN_HEIGHT / 2 - 565 / 2

		------------ CardSlot(cardslot.lua)
		CARDSLOT_OFFX = SCREEN_WIDTH / 2 - 147
		CARDSLOT_OFFY = SCREEN_HEIGHT / 2 - 282

		------------ Survey(surveyui.lua)
		SURVEY_VIEW_OFFX = 319
		SURVEY_VIEW_OFFY = 112
		SURVEY_CONF_OFFX = 339
		SURVEY_CONF_OFFY = 324

		------------ Screen Shot Offset
		SCREEN_SHOT_OFFX = SCREEN_WIDTH / 2 - 350 / 2
		SCREEN_SHOT_OFFY = SCREEN_HEIGHT - 85

		------------ Npc_Talk
		NPC_TALK_OFFX = SCREEN_WIDTH / 2 - 400
		NPC_TALK_OFFY = SCREEN_HEIGHT - 378

		dofile("UI\\common_ui.lua")

		SCREEN_WIDTH = $SCREEN_WIDTH
		SCREEN_HEIGHT = $SCREEN_HEIGHT   

		-- Square Screen
		dofile("UI\\square_screen.lua")	

		SCREEN_WIDTH = $SCREEN_WIDTH
		SCREEN_HEIGHT = $SCREEN_HEIGHT   

	)";
#else
	inline std::string squareInitLua = R"(

		dofile('UI\\GlobalVar.lua')
		dofile('UI\\mnemonic.lua')
		dofile('UI\\StringTable.lua')
		dofile('UI\\common_res.lua')
		dofile('UI\\square_id.lua')

		SCREEN_WIDTH = $SCREEN_WIDTH
		SCREEN_HEIGHT = $SCREEN_HEIGHT

		MAINBAR_OFFX = 1074
		MAINBAR_OFFY = SCREEN_HEIGHT - 69

		MAINMENU_OFFX = 1111
		MAINMENU_OFFY = 1

		SQMINIMAP_OFFX = SCREEN_WIDTH - 225
		SQMINIMAP_OFFY = 35

		SQUARE_NAME_OFFX = 531
		SQUARE_NAME_WIDTH = 0

		SQTIP_OFFX = 0
		SQTIP_OFFY = SCREEN_HEIGHT - 74
		SQTIP_WIDTH = SCREEN_WIDTH - 236

		FIRSTSQ_UPPER_OFFX = SCREEN_WIDTH / 2 - 400
		FIRSTSQ_UPPER_OFFY = 0

		FIRSTSQ_LOWER_OFFX = SCREEN_WIDTH / 2 - 400
		FIRSTSQ_LOWER_OFFY = SCREEN_HEIGHT - 240

		MSG_CONNECTFRIEND_OFFX = 599
		MSG_CONNECTFRIEND_OFFY = 410

		FUNCITEM_OFFX = 339
		FUNCITEM_OFFY = 263

		MY_INVEN_OFFX = SCREEN_WIDTH / 2 - 800 / 2
		MY_INVEN_OFFY = SCREEN_HEIGHT / 2 - 407 / 2

		OTHER_TRADE_OFFX = SCREEN_WIDTH / 2 - 800 / 2 + 636
		OTHER_TRADE_OFFY = SCREEN_HEIGHT / 2 - 407 / 2

		CARDSLOT_OFFX = 493
		CARDSLOT_OFFY = 230

		SURVEY_VIEW_OFFX = 319
		SURVEY_VIEW_OFFY = 112

		SURVEY_CONF_OFFX = 339
		SURVEY_CONF_OFFY = 324

		SCREEN_SHOT_OFFX = SCREEN_WIDTH / 2 - 350 / 2
		SCREEN_SHOT_OFFY = SCREEN_HEIGHT - 85

		NPC_TALK_OFFX = SCREEN_WIDTH / 2 - 400
		NPC_TALK_OFFY = SCREEN_HEIGHT - 378

		SQCHATVIEW_OFFX = 240
		SQCHATVIEW_OFFY = SCREEN_HEIGHT - 84 - 101

		SQCHATEDIT_OFFX = 240
		SQCHATEDIT_OFFY = SCREEN_HEIGHT - 84

		MSG_OFFX = SCREEN_WIDTH / 2 + 795 / 2 - 287 
		MSG_OFFY = SCREEN_HEIGHT - 368

		MSG_FRLIST_OFFX = MSG_OFFX - 322 - 15
		MSG_FRLIST_OFFY = SCREEN_HEIGHT - 368

		MSG_MEMO_OFFX = MSG_OFFX - 322 - 15
		MSG_MEMO_OFFY = SCREEN_HEIGHT - 368

		MSG_MEMOVIEW_OFFX = MSG_OFFX - 322 - 15
		MSG_MEMOVIEW_OFFY = SCREEN_HEIGHT - 368

		MSG_MEMOEDIT_OFFX = MSG_OFFX - 322 - 15
		MSG_MEMOEDIT_OFFY = SCREEN_HEIGHT - 368

		INVENTORY_OFFX = SCREEN_WIDTH / 2 - 330 / 2
		INVENTORY_OFFY = SCREEN_HEIGHT / 2 - 500 / 2

		CHARVIEW_OFFX = SCREEN_WIDTH / 2 - 230 - 330 / 2
		CHARVIEW_OFFY = SCREEN_HEIGHT / 2 - 500 / 2

		NOTEBOX_OFFX = 1101
		NOTEBOX_OFFY = 937

		dofile('UI\\common_ui.lua')
		--dofile('UI\\square_screen.lua') BELOW:

		dofile("UI\\inventory.lua")
		dofile("UI\\buygift.lua")
		dofile("UI\\cardshop.lua")
		dofile("UI\\server_select.lua")
		dofile("UI\\cardslot.lua")
		dofile("UI\\character_view.lua")

		SCREEN_WIDTH = $SCREEN_WIDTH - 117 * 2
		SCREEN_HEIGHT = $SCREEN_HEIGHT + 49 * 2

		dofile("UI\\roomlist.lua")

		SCREEN_WIDTH = $SCREEN_WIDTH
		SCREEN_HEIGHT = $SCREEN_HEIGHT

		dofile("UI\\makeroom.lua")
		dofile("UI\\NoteBox.lua")
		dofile("UI\\character_create.lua")
		dofile("UI\\currentstate_res.lua")
		dofile("UI\\currentstate.lua")
		dofile("UI\\admin_announce.lua")
		dofile("UI\\infotitle.lua")
		dofile("UI\\viewcardset.lua")
		dofile("UI\\newsui.lua")
		dofile("UI\\guide.lua")
		dofile("UI\\option.lua")
		dofile("UI\\messenger.lua")

		dofile("UI\\tutorialsel.lua")
		dofile("UI\\funcitem.lua")
		dofile("UI\\ingame_res.lua")
		dofile("UI\\squarebar.lua")
		dofile("UI\\squarelist.lua")

		--dofile("UI\\Square_chatting.lua") BELOW:

		dofile("UI\\Square_chatting_res.lua")
		dofile("UI\\legacy_square_chatting_res.lua")

		if(CURRENT_STATE == STATE_GAMEROOM) then
			SQCHATVIEW_OFFX = 100

		dofile("UI\\legacy_lobby_chatting_res.lua")

		CreateDialog(UI_IDD_SQCHAT, 236, 350 , 368 ,167 , NULL_WINDOW_TITLE , 5 , LEGACY_COMMON_RES_BASE+0 , UIRECT_NINE)
			EnableSkinColor(UI_IDD_SQCHAT)
		CreateCaptionBar(UI_IDD_SQCHAT , UI_IDC_LOBBY_CHATTING_CAPTION, 14 , -22 , 112 , 24 ,4, LEGACY_COMMON_RES_BASE+0 , UIRECT_THREE)
		CreatePictureBox(UI_IDD_SQCHAT , UI_IDP_LOBBY_CHATTING_CAPTION, 16 , 2 , 108 , 22 , 1 , LEGACY_LOBBY_CHATTING_RES_BASE+0, UIRECT_ONE)
		CreateWorkGroupBox(UI_IDD_SQCHAT , UI_IDP_SQCHAT_INNERBOX , 13, 35 ,  326 , 118 , 10 , LEGACY_COMMON_RES_BASE+0 , UIRECT_NINE)    
		CreateWorkGroupBox(UI_IDD_SQCHAT , UI_IDP_SQCHAT_INNERBOX_DUMMY , 13, 35 ,  326 , 118 , 10 , LEGACY_COMMON_RES_BASE+0 , UIRECT_NINE)    

		CreatePictureBox(UI_IDD_GAMEROOM_FRAME, UI_IDP_SQCHAT_SCRBG, -9999, 414, 15, 118, 8, COMMON_RES_BASE+69, UIRECT_THREE) 
		CreateScrollBar(UI_IDD_GAMEROOM_FRAME , UI_IDS_SQCHAT_SCROLL , 340 , 414 , 15 , 118 , 6, LEGACY_COMMON_RES_BASE+0 , LEGACY_COMMON_RES_BASE+3, LEGACY_COMMON_RES_BASE+4)
		CreateListBox(UI_IDD_SQCHAT , UI_IDL_SQCHAT_VIEW , 20 ,  133 , 312 , 15 , 0 , LEGACY_COMMON_RES_BASE+3 , UIRECT_NONE)
			ControlTextDir(UI_IDL_SQCHAT_VIEW, TextDir_Left)
			ListBoxAddScroll(UI_IDL_SQCHAT_VIEW , UI_IDS_SQCHAT_SCROLL)
			ListBoxSetLimit(UI_IDL_SQCHAT_VIEW, TRUE , 50, 6 )
		CreateNullDialog(UI_IDD_SQEDIT, 249, 483, 342, 21, 4)
		CreateMultiLangEditBox(UI_IDD_SQCHAT, UI_IDE_SQEDIT_INPUT, 13, 155, 342, 21, STR_CONTROL_NULL, 2, LEGACY_COMMON_RES_BASE+0, UIRECT_THREE)
		CreateMultiLangEditBox(UI_IDD_SQCHAT, UI_IDE_SQEDIT_INPUTBK, 13, 155, 342, 21, STR_CONTROL_NULL, 3, SQUARE_RES_BASE+251, UIRECT_ONE)
		CreateSkinnedPictureBox(UI_IDD_SQCHAT, UI_IDP_LOBBY_CHATTING_RUNNER, 40, 22, 15, 15, 5, LEGACY_COMMON_RES_BASE+0, UIRECT_ONE)
		CreateSkinnedPictureBox(UI_IDD_SQCHAT, UI_IDP_LOBBY_CHATTING_RUNNER, 297, 22, 15, 15, 5, LEGACY_COMMON_RES_BASE+0, UIRECT_ONE)
		CreateSkinnedPictureBox(UI_IDD_SQCHAT, UI_IDP_LOBBY_CHATTING_RUNNER, 340, 22, 15, 15, 5, LEGACY_COMMON_RES_BASE+0, UIRECT_ONE)
		CreateSkinnedPictureBox(UI_IDD_SQCHAT, UI_IDP_LOBBY_CHATTING_RUNNER, 40, 174, 15, 15, 5, LEGACY_COMMON_RES_BASE+1, UIRECT_ONE)
		CreateSkinnedPictureBox(UI_IDD_SQCHAT, UI_IDP_LOBBY_CHATTING_RUNNER, 313, 174, 15, 15, 5, LEGACY_COMMON_RES_BASE+1, UIRECT_ONE)

		SQTIP_WIDTH = 450
		CreateNullDialog(UI_IDD_SQTIP, 234, 0, SQTIP_WIDTH, 23, 10)
		CreatePictureBox(UI_IDD_SQTIP, UI_IDP_SQTIP_BACK, 0, 2, SQTIP_WIDTH, 23, 8, LEGACY_SQUARE_RES_BASE+271, UIRECT_THREE)
		CreatePictureBox(UI_IDD_SQTIP, UI_IDP_SQTIP_CAPTION, 2, 4, 77, 19, 7, LEGACY_SQUARE_RES_BASE+272, UIRECT_ONE)
		CreateTipBox(UI_IDD_SQTIP, UI_IDS_SQTIP_TIPBOX, 85, 4, SQTIP_WIDTH-100, 19, 6, LEGACY_SQUARE_RES_BASE+273, UIRECT_NONE)
			ControlTextDir(UI_IDS_SQTIP_TIPBOX, TextDir_Left)
			SetTextGap(UI_IDS_SQTIP_TIPBOX, 7, 6)

			CreateButton(UI_IDD_SQCHAT, UI_IDB_SQCHAT_BTN_SIZE, -9999, 4, 23, 16, "", 9, COMMON_RES_BASE+6, UIRECT_ONE)
			CreateRadioButton(UI_IDD_SQCHAT, UI_IDR_SQCHAT_TAB_GENERAL, -9999, 0, 60, 20, 9, SQUARE_RES_BASE+274, UIRECT_NINE)
			CreateStatic(UI_IDD_SQCHAT, UI_IDS_SQCHAT_TAB_GENERAL, -9999, 5, 58, 12, "General", 8, COMMON_RES_BASE+0, UIRECT_NONE)
				StaticTextDir(UI_IDS_SQCHAT_TAB_GENERAL, TextDir_vCenter)  
			CreateRadioButton(UI_IDD_SQCHAT, UI_IDR_SQCHAT_TAB_NOTE, -9999, 0, 60, 20, 9, SQUARE_RES_BASE+274, UIRECT_NINE)
			CreateStatic(UI_IDD_SQCHAT, UI_IDS_SQCHAT_TAB_NOTE, -9999, 8, 58, 12, "Note", 8, COMMON_RES_BASE+0, UIRECT_NONE)
				StaticTextDir(UI_IDS_SQCHAT_TAB_NOTE, TextDir_vCenter)  
				SetRadioButtonGroup(UI_IDR_SQCHAT_TAB_GENERAL, 0)
				SetRadioButtonGroup(UI_IDR_SQCHAT_TAB_NOTE, 0)
			CreatePanoramaPictureBox(UI_IDD_SQCHAT, UI_IDP_SQCHAT_NEWMEMO, -9999, -10, 25, 20, 0, SQUARE_RES_BASE+203, UIRECT_ONE)
		else

		CreateNullDialog(UI_IDD_SQCHAT, 5, SQCHATVIEW_OFFY, 358, 100, 10)
		offy = 436
		CreateButton(UI_IDD_SQCHAT, UI_IDB_SQCHAT_BTN_SIZE, 277 - 9999, 4, 23, 16, "", 9, COMMON_RES_BASE+6, UIRECT_ONE)
		CreatePictureBox(UI_IDD_SQCHAT, UI_IDP_SQCHAT_INNERBOX, 3, 0, 355, 100, 10, LEGACY_SQUARE_RES_BASE+201, UIRECT_NINE)    
		CreatePictureBox(UI_IDD_SQCHAT, UI_IDP_SQCHAT_SCRBG, 339, 439 - offy, 15, 94, 9, LEGACY_SQUARE_RES_BASE+202, UIRECT_THREE)
		CreateScrollBar(UI_IDD_SQCHAT, UI_IDS_SQCHAT_SCROLL, 340, 441 - offy, 13, 90, 6, LEGACY_SQUARE_RES_BASE+203, LEGACY_SQUARE_RES_BASE+204, LEGACY_SQUARE_RES_BASE+205)    
			CreateRadioButton(UI_IDD_SQCHAT, UI_IDR_SQCHAT_TAB_GENERAL, 0, 0, 60, 20, 9, SQUARE_RES_BASE+274, UIRECT_NINE)
				SetVisible(UI_IDR_SQCHAT_TAB_GENERAL, FALSE)
			CreateStatic(UI_IDD_SQCHAT, UI_IDS_SQCHAT_TAB_GENERAL, 3, 5, 58, 12, "General", 8, COMMON_RES_BASE+0, UIRECT_NONE)
				SetVisible(UI_IDS_SQCHAT_TAB_GENERAL, FALSE)
				StaticTextDir(UI_IDS_SQCHAT_TAB_GENERAL, TextDir_vCenter)  
			CreateRadioButton(UI_IDD_SQCHAT, UI_IDR_SQCHAT_TAB_NOTE, 59, 0, 60, 20, 9, SQUARE_RES_BASE+274, UIRECT_NINE)
				SetVisible(UI_IDR_SQCHAT_TAB_NOTE, FALSE)
			CreateStatic(UI_IDD_SQCHAT, UI_IDS_SQCHAT_TAB_NOTE, 62, 8, 58, 12, "Note", 8, COMMON_RES_BASE+0, UIRECT_NONE)
				SetVisible(UI_IDS_SQCHAT_TAB_NOTE, FALSE)
				StaticTextDir(UI_IDS_SQCHAT_TAB_NOTE, TextDir_vCenter)  
				SetRadioButtonGroup(UI_IDR_SQCHAT_TAB_GENERAL, 0)
				SetRadioButtonGroup(UI_IDR_SQCHAT_TAB_NOTE, 0)
		CreateListBox(UI_IDD_SQCHAT, UI_IDL_SQCHAT_VIEW, 13, 515-offy, 310, 15, 6, LEGACY_SQUARE_RES_BASE+221, UIRECT_NONE)
			ControlTextDir(UI_IDL_SQCHAT_VIEW, TextDir_Left)
			ListBoxAddScroll(UI_IDL_SQCHAT_VIEW, UI_IDS_SQCHAT_SCROLL)
			ListBoxSetLimit(UI_IDL_SQCHAT_VIEW, TRUE, 200, 5)
			CreatePanoramaPictureBox(UI_IDD_SQCHAT, UI_IDP_SQCHAT_NEWMEMO, 25+59 - 9999, -10, 25, 20, 0, SQUARE_RES_BASE+203, UIRECT_ONE)
		CreateNullDialog(UI_IDD_SQEDIT, 5, SQCHATEDIT_OFFY, 358, 19, 10)
		offy = 538
		CreateMultiLangEditBox(UI_IDD_SQEDIT, UI_IDE_SQEDIT_INPUT, 3, 0, 355, 19, STR_CONTROL_NULL, 3, LEGACY_SQUARE_RES_BASE+251, UIRECT_THREE)
		CreateMultiLangEditBox(UI_IDD_SQEDIT, UI_IDE_SQEDIT_INPUTBK, 3, 0, 355, 19, STR_CONTROL_NULL, 3, LEGACY_SQUARE_RES_BASE+251, UIRECT_THREE)
		CreateNullDialog(UI_IDD_SQTIP, 234, 0, SQTIP_WIDTH, 23, 10)
		CreatePictureBox(UI_IDD_SQTIP, UI_IDP_SQTIP_BACK, 0, 2, SQTIP_WIDTH, 23, 8, LEGACY_SQUARE_RES_BASE+271, UIRECT_THREE)
		CreatePictureBox(UI_IDD_SQTIP, UI_IDP_SQTIP_CAPTION, 2, 4, 77, 19, 7, LEGACY_SQUARE_RES_BASE+272, UIRECT_ONE)

		SQTIP_WIDTH = 450
		CreateTipBox(UI_IDD_SQTIP, UI_IDS_SQTIP_TIPBOX, 85, 4, SQTIP_WIDTH-100, 19, 6, LEGACY_SQUARE_RES_BASE+273, UIRECT_NONE)
			ControlTextDir(UI_IDS_SQTIP_TIPBOX, TextDir_Left)
			SetTextGap(UI_IDS_SQTIP_TIPBOX, 7, 6)
		end

		CreateNullDialog(UI_IDD_MEMOLIST, MSG_MEMO_OFFX, MSG_MEMO_OFFY, 300, 140, 10)

			CreatePictureBox(UI_IDD_MEMOLIST, UI_IDP_MEMOLIST_SCRBG, 292, 45, 6, 93, 6, COMMON_RES_BASE+69, UIRECT_THREE)
			CreateScrollBar(UI_IDD_MEMOLIST, UI_IDS_MEMOLIST_SCR, 292, 45, 6, 93, 5, COMMON_RES_BASE+2, COMMON_RES_BASE+5, COMMON_RES_BASE+5)

			CreateWorkGroupBox(UI_IDD_MEMOLIST, UI_IDP_MEMOLIST_INNER, 0, 19, 300, 121, 9, COMMON_RES_BASE+0, UIRECT_NINE) 
	
			CreateWorkGroupBox(UI_IDD_MEMOLIST, UI_IDP_MEMOLIST_INNER, 0, 19, 300, 25, 9, COMMON_RES_BASE+24, UIRECT_NINE) 

			CreateCheckBox(UI_IDD_MEMOLIST, UI_IDC_MEMOLIST_CHECKALL, 4, 27, 10, 10, FALSE, 6, COMMON_RES_BASE+2, UIRECT_ONE)
			CreateStatic(UI_IDD_MEMOLIST, UI_IDS_MEMOLIST_CHECKALL, 18, 26, 140, 12, "Select All", 7, COMMON_RES_BASE+0, UIRECT_NONE)
				StaticTextDir(UI_IDS_MEMOLIST_CHECKALL, TextDir_vLeft)
		
			CreateButton(UI_IDD_MEMOLIST, UI_IDB_MEMOLIST_SELDEL, 230, 25, 65, 13, "delete", 6, COMMON_RES_BASE+16, UIRECT_ONE)
	
			CreateWorkGroupBox(UI_IDD_MEMOLIST, UI_IDW_MEMOLIST_BLUEBG1, 1, 44, 298, 19, 8, COMMON_RES_BASE+6, UIRECT_NINE)
	
			CreateCheckBox(UI_IDD_MEMOLIST, UI_IDC_MEMOLIST_CHECK1, 4, 48, 10, 10, FALSE, 6, COMMON_RES_BASE+3, UIRECT_ONE)
	
			CreateButton(UI_IDD_MEMOLIST, UI_IDB_MEMOLIST_CONTENT1, 17, 47, 249, 12, STR_NULL, 6, COMMON_RES_BASE+15, UIRECT_ONE) 
				SetTextGap(UI_IDB_MEMOLIST_CONTENT1, 0, 0)    
				ControlTextDir(UI_IDB_MEMOLIST_CONTENT1, TextDir_vLeft)
		
			CreateButton(UI_IDD_MEMOLIST, UI_IDB_MEMOLIST_REPLYBTN1, 268, 48, 10, 10, STR_NULL, 6, COMMON_RES_BASE+11, UIRECT_ONE)
			CreateButton(UI_IDD_MEMOLIST, UI_IDB_MEMOLIST_DELBTN1, 280, 48, 10, 10, STR_NULL, 6, COMMON_RES_BASE+9, UIRECT_ONE)
		
			CreatePictureBox(UI_IDD_MEMOLIST, UI_IDP_MEMOLIST_INNER, 1, 63, 298, 19, 9, COMMON_RES_BASE+2, UIRECT_ONE)
	
			CreateWorkGroupBox(UI_IDD_MEMOLIST, UI_IDW_MEMOLIST_BLUEBG2, 1, 63, 298, 19, 8, COMMON_RES_BASE+6, UIRECT_NINE) 
	
			CreateCheckBox(UI_IDD_MEMOLIST, UI_IDC_MEMOLIST_CHECK2, 4, 67, 10, 10, FALSE, 6, COMMON_RES_BASE+3, UIRECT_ONE)

			CreateButton(UI_IDD_MEMOLIST, UI_IDB_MEMOLIST_CONTENT2, 17, 66, 249, 12,STR_NULL, 6, COMMON_RES_BASE+15, UIRECT_ONE)
				SetTextGap(UI_IDB_MEMOLIST_CONTENT2, 0, 0)
				ControlTextDir(UI_IDB_MEMOLIST_CONTENT2, TextDir_vLeft)
		
			CreateButton(UI_IDD_MEMOLIST, UI_IDB_MEMOLIST_REPLYBTN2, 268, 67, 10, 10, STR_NULL, 6, COMMON_RES_BASE+11, UIRECT_ONE)
			CreateButton(UI_IDD_MEMOLIST, UI_IDB_MEMOLIST_DELBTN2, 280, 67, 10, 10, STR_NULL, 6, COMMON_RES_BASE+9, UIRECT_ONE)
		
			CreateWorkGroupBox(UI_IDD_MEMOLIST, UI_IDW_MEMOLIST_BLUEBG3, 1, 82, 298, 19, 8, COMMON_RES_BASE+6, UIRECT_NINE) 
	
			CreateCheckBox(UI_IDD_MEMOLIST, UI_IDC_MEMOLIST_CHECK3, 4, 86, 10, 10, FALSE, 6, COMMON_RES_BASE+3, UIRECT_ONE)

			CreateButton(UI_IDD_MEMOLIST, UI_IDB_MEMOLIST_CONTENT3, 17, 87, 249, 12, STR_NULL, 6, COMMON_RES_BASE+15,UIRECT_ONE)
				ControlTextDir(UI_IDB_MEMOLIST_CONTENT3, TextDir_vLeft)
		
			CreateButton(UI_IDD_MEMOLIST, UI_IDB_MEMOLIST_REPLYBTN3, 268, 86, 10, 10, STR_NULL, 6, COMMON_RES_BASE+11, UIRECT_ONE)
			CreateButton(UI_IDD_MEMOLIST, UI_IDB_MEMOLIST_DELBTN3, 280, 86, 10, 10, STR_NULL, 6, COMMON_RES_BASE+9, UIRECT_ONE)
		
			CreatePictureBox(UI_IDD_MEMOLIST, UI_IDP_MEMOLIST_INNER, 1, 101, 298, 19, 9, COMMON_RES_BASE+2, UIRECT_ONE) 
	
			CreateWorkGroupBox(UI_IDD_MEMOLIST, UI_IDW_MEMOLIST_BLUEBG4, 1, 101, 298, 19, 8, COMMON_RES_BASE+6, UIRECT_NINE) 
	
			CreateCheckBox(UI_IDD_MEMOLIST, UI_IDC_MEMOLIST_CHECK4, 4, 105, 10, 10, FALSE, 6, COMMON_RES_BASE+3, UIRECT_ONE)

			CreateButton(UI_IDD_MEMOLIST, UI_IDB_MEMOLIST_CONTENT4, 17, 104, 249, 12, STR_NULL, 6, COMMON_RES_BASE+15,UIRECT_ONE)
				ControlTextDir(UI_IDB_MEMOLIST_CONTENT4, TextDir_vLeft)
		
			CreateButton(UI_IDD_MEMOLIST, UI_IDB_MEMOLIST_REPLYBTN4, 268, 105, 10, 10, STR_NULL, 6, COMMON_RES_BASE+11, UIRECT_ONE)
			CreateButton(UI_IDD_MEMOLIST, UI_IDB_MEMOLIST_DELBTN4, 280, 105, 10, 10, STR_NULL, 6, COMMON_RES_BASE+9, UIRECT_ONE)
		
			CreateWorkGroupBox(UI_IDD_MEMOLIST, UI_IDW_MEMOLIST_BLUEBG5, 1, 120, 298, 19, 8, COMMON_RES_BASE+6, UIRECT_NINE) 
	
			CreateCheckBox(UI_IDD_MEMOLIST, UI_IDC_MEMOLIST_CHECK5, 4, 124, 10, 10, FALSE, 6, COMMON_RES_BASE+3, UIRECT_ONE)

			CreateButton(UI_IDD_MEMOLIST, UI_IDB_MEMOLIST_CONTENT5, 17, 123, 249, 12,STR_NULL, 6, COMMON_RES_BASE+15,UIRECT_ONE)
				ControlTextDir(UI_IDB_MEMOLIST_CONTENT5, TextDir_vLeft)
		
			CreateButton(UI_IDD_MEMOLIST, UI_IDB_MEMOLIST_REPLYBTN5, 268, 124, 10, 10, STR_NULL, 6, COMMON_RES_BASE+11, UIRECT_ONE)
			CreateButton(UI_IDD_MEMOLIST, UI_IDB_MEMOLIST_DELBTN5, 280, 124, 10, 10, STR_NULL, 6, COMMON_RES_BASE+9, UIRECT_ONE)

		CreateNullDialog(UI_IDD_MEMOVIEW, MSG_MEMOVIEW_OFFX, MSG_MEMOVIEW_OFFY, 300, 121, 5)


			CreateWorkGroupBox(UI_IDD_MEMOVIEW, UI_IDW_MEMOVIEW_BG, 0, 0, 300, 121, 5, COMMON_RES_BASE+0, UIRECT_NINE)
				SetVertexColor(UI_IDW_MEMOVIEW_BG, 190, 255, 255, 255)
		
			CreateWorkGroupBox(UI_IDD_MEMOVIEW, UI_IDW_MEMOVIEW_BG, 0, 0, 300, 25, 4, COMMON_RES_BASE+24, UIRECT_NINE)

			CreateStatic(UI_IDD_MEMOVIEW, UI_IDS_MEMOVIEW_SENDER, 5, 8, 140, 12, "", 1, COMMON_RES_BASE+0, UIRECT_NONE)
				StaticTextDir(UI_IDS_MEMOVIEW_SENDER, TextDir_vLeft)
				SetTextGap(UI_IDS_MEMOVIEW_SENDER, 7, 6) 

			CreateStatic(UI_IDD_MEMOVIEW, UI_IDS_MEMOVIEW_MSG, 5, 32, 290, 67, "", 1, COMMON_RES_BASE+0, UIRECT_NONE)

			CreateButton(UI_IDD_MEMOVIEW, UI_IDB_MEMOVIEW_REPLY, 271, 9, 10, 10, STR_NULL, 2, COMMON_RES_BASE+11, UIRECT_ONE)
			CreateButton(UI_IDD_MEMOVIEW, UI_IDB_MEMOVIEW_CLOSE, 285, 9, 10, 10, STR_NULL, 2, COMMON_RES_BASE+9, UIRECT_ONE)
			CreateButton(UI_IDD_MEMOVIEW, UI_IDB_MEMOVIEW_DEL, 230, 103, 65, 13, STR_NULL, 2, COMMON_RES_BASE+16, UIRECT_ONE))"

		R"(

		CreateNullDialog(UI_IDD_MEMOEDIT, MSG_MEMOEDIT_OFFX, MSG_MEMOEDIT_OFFY, 300, 121, 5)
			CreateWorkGroupBox(UI_IDD_MEMOEDIT, UI_IDW_MEMOEDIT_BG, 0, 0, 300, 121, 5, COMMON_RES_BASE+0, UIRECT_NINE) 
				SetVertexColor(UI_IDW_MEMOEDIT_BG, 190, 255, 255, 255) 

			CreateWorkGroupBox(UI_IDD_MEMOEDIT, UI_IDW_MEMOEDIT_BG, 0, 0, 300, 25, 4, COMMON_RES_BASE+24, UIRECT_NINE)

			CreateStatic(UI_IDD_MEMOEDIT, UI_IDS_MEMOEDIT_NICK, 5, 8, 140, 12, "", 1, COMMON_RES_BASE+0, UIRECT_NONE)
				StaticTextDir(UI_IDS_MEMOEDIT_NICK, TextDir_vLeft)
				SetTextGap(UI_IDS_MEMOEDIT_NICK, 7, 6)

			CreatePictureBox(UI_IDD_MEMOEDIT, UI_IDW_MEMOEDIT_BG, 221, 8, 65, 13, 9, COMMON_RES_BASE+70, UIRECT_ONE)
	
			CreateStatic(UI_IDD_MEMOEDIT, UI_IDS_MEMOEDIT_STAT, 226, 8, 55, 12, "", 1, COMMON_RES_BASE+0, UIRECT_NONE)
				StaticTextDir(UI_IDS_MEMOEDIT_STAT, TextDir_vCenter)
				SetTextGap(UI_IDS_MEMOEDIT_STAT, 7, 6)

			CreateMultiLangEditBox( UI_IDD_MEMOEDIT, UI_IDE_MEMOEDIT_EDIT, 5, 32, 290, 20, STR_CONTROL_NULL, 1, COMMON_RES_BASE+1, UIRECT_NONE)        

			CreateButton(UI_IDD_MEMOEDIT, UI_IDB_MEMOEDIT_CANCEL, 285, 9, 10, 10, STR_NULL, 2, COMMON_RES_BASE+9, UIRECT_ONE)
			CreateButton(UI_IDD_MEMOEDIT, UI_IDB_MEMOEDIT_SEND, 230, 103, 65, 13, STR_NULL, 2, COMMON_RES_BASE+16, UIRECT_ONE)

		dofile("UI\\SquareMap.lua")
		dofile("UI\\FirstInSquare.lua")
		dofile("UI\\surveyui.lua")
		dofile("UI\\UserTrade.lua")
		dofile("UI\\itemCrane.lua")
		dofile("UI\\enchant.lua")
		dofile("UI\\UserOpenReward.lua")
		dofile("UI\\npctalkui.lua")

		MAX_PLAYER_IN_SQUARE = 69

		for i = 0, MAX_PLAYER_IN_SQUARE, 1 do    
			ID_OFFSET = (UI_IDD_SQUARENAME2-UI_IDD_SQUARENAME1)*i
			IDD_TAG = UI_IDD_SQUARENAME1+ID_OFFSET
			IDT_NICK = UI_IDT_SQUARENAME1_NICK+ID_OFFSET
			IDP_EXP = UI_IDP_SQUARENAME1_EXP+ID_OFFSET
	
			CreateNullDialog( IDD_TAG, 0, 0, 140, 30, 13)
			CreateText(IDD_TAG, IDT_NICK, 23, 9, 117, 30, 1, GAME_RES_BASE+0)
				ControlTextDir(IDT_NICK, TextDir_Left)
			CreatePictureBox(IDD_TAG, IDP_EXP, 0, 6, 19, 19, 1, CHARVIEW_RES_BASE+0, UIRECT_ONE)		

			HideDialog(IDD_TAG)
		end
	
		for i = 0, MAX_PLAYER_IN_SQUARE, 1 do
			ID_OFFSET = (UI_IDD_BATTLEPIC2-UI_IDD_BATTLEPIC1)*i		
			ID_BATTLEPIC = UI_IDD_BATTLEPIC1 + ID_OFFSET
			CreateNullDialog(ID_BATTLEPIC, 0, 0, 45, 46, 15)
			CreatePictureBox(ID_BATTLEPIC, ID_BATTLEPIC+1, 0, 0, 45, 46, 10, LEGACY_COMMON_RES_BASE+54, UIRECT_ONE)
		end	

		for i = 0, MAX_PLAYER_IN_SQUARE, 1 do
			ID_OFFSET = (UI_IDD_BUBBLETAG2-UI_IDD_BUBBLETAG1)*i		
			ID_BUBBLETAG = UI_IDD_BUBBLETAG1 + ID_OFFSET
			CreateSqChatDlg(ID_BUBBLETAG, LEGACY_COMMON_RES_BASE+21, LEGACY_COMMON_RES_BASE+21)
		end	

		for i = 0, MAX_PLAYER_IN_SQUARE, 1 do
			ID_OFFSET = (UI_IDD_EMOTICON2-UI_IDD_EMOTICON1)*i		
			IDD_EMOTICON = UI_IDD_EMOTICON1 + ID_OFFSET
			IDP_EMOTICONPIC = UI_IDP_EMOTICON1_EMOTION + ID_OFFSET
	
			CreateNullDialog(IDD_EMOTICON, 0, 0, 64, 64, 13)
			CreatePictureBox(IDD_EMOTICON, IDP_EMOTICONPIC, 0, 0, 64, 64, 1, COMMON_RES_BASE+56, UIRECT_ONE)
		end

		AllDialogSortingLayer()

		CreateDialog(UI_IDD_BACK, 0, 0, SCREEN_WIDTH, SCREEN_HEIGHT, NULL_WINDOW_TITLE, 9500, 0, UIRECT_ONE)

		CreateNullDialog( UI_IDD_SCREENSHOT, SCREEN_SHOT_OFFX, SCREEN_SHOT_OFFY, 450, 20, -2 )
		CreateStatic(UI_IDD_SCREENSHOT , UI_IDS_SCREENSHOT, 0, 0 , 450 , 20 , STR_NULL, -1, LEGACY_COMMON_RES_BASE+17,UIRECT_NONE)
			StaticTextDir(UI_IDS_SCREENSHOT, TextDir_Left)

	)";
#endif
}